#!/usr/bin/env bash
# Display Best School

i=1

while [ $i -lt "10" ]
do
    echo "Holberton School"

    if [ $i -eq "9" ]
    then
        echo "Hi"
        echo "Best School"
    fi

    ((i += 1))
done

