#!/usr/bin/env bash
# Displays the time for 12 hour

hour=0
min=1

while [ $hour -le "12" ] ; do
    echo "Hour: $hour"
    (("min=1"))

    while [ $min -le "59" ] ; do
        echo $min
        (("min += 1"))
    done

    (("hour += 1"))
done
